INSERT INTO DEVICE_TYPE(ID, COST, NAME) VALUES (1, 4, 'Windows Workstation');
INSERT INTO DEVICE_TYPE(ID, COST, NAME) VALUES (2, 4, 'Windows Server');
INSERT INTO DEVICE_TYPE(ID, COST, NAME) VALUES (3, 4, 'Mac');

INSERT INTO SERVICE(ID, COST, NAME) VALUES (1, 5, 'Windows Antivirus');
INSERT INTO SERVICE(ID, COST, NAME) VALUES (2, 7, 'Mac Antivirus');
INSERT INTO SERVICE(ID, COST, NAME) VALUES (3, 3, 'Backup');
INSERT INTO SERVICE(ID, COST, NAME) VALUES (4, 2, 'PSA');
INSERT INTO SERVICE(ID, COST, NAME) VALUES (5, 1, 'Screen Share');

